-- Upgrade MetaStore schema from 3.1.3000.7.2.15.0-Update5 to 3.1.3000.7.2.15.0-Update6

-- HIVE-26049
ALTER TABLE "APP"."TXN_COMPONENTS" ALTER "TC_TABLE" SET DATA TYPE VARCHAR(256);
ALTER TABLE "APP"."HIVE_LOCKS" ALTER "HL_TABLE" SET DATA TYPE VARCHAR(256);
ALTER TABLE "APP"."COMPACTION_QUEUE" ALTER "CQ_TABLE" SET DATA TYPE VARCHAR(256);
ALTER TABLE "APP"."COMPLETED_COMPACTIONS" ALTER "CC_TABLE" SET DATA TYPE VARCHAR(256);
ALTER TABLE "APP"."WRITE_SET" ALTER "WS_TABLE" SET DATA TYPE VARCHAR(256);
ALTER TABLE "APP"."TXN_WRITE_NOTIFICATION_LOG" ALTER "WNL_TABLE" SET DATA TYPE VARCHAR(256);

-- These lines need to be last.  Insert any changes above.
UPDATE "APP".CDH_VERSION SET SCHEMA_VERSION='3.1.3000.7.2.15.0-Update6', VERSION_COMMENT='Hive release version 3.1.3000 for CDH 7.2.15.0-Update6' where VER_ID=1;
