SELECT 'Upgrading MetaStore schema from 3.1.3000.7.2.15.0-Update6 to 7.2.16.0-Update1' AS Status from dual;

-- HIVE-24396
-- Create DataConnectors and DataConnector_Params tables
CREATE TABLE DATACONNECTORS (
  NAME VARCHAR2(128) NOT NULL,
  TYPE VARCHAR2(32) NOT NULL,
  URL VARCHAR2(4000) NOT NULL,
  "COMMENT" VARCHAR2(256),
  OWNER_NAME VARCHAR2(256),
  OWNER_TYPE VARCHAR2(10),
  CREATE_TIME NUMBER(10) NOT NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE DATACONNECTOR_PARAMS (
  NAME VARCHAR2(128) NOT NULL,
  PARAM_KEY VARCHAR2(180) NOT NULL,
  PARAM_VALUE VARCHAR2(4000),
  PRIMARY KEY (NAME, PARAM_KEY),
  CONSTRAINT DATACONNECTOR_NAME_FK1 FOREIGN KEY (NAME) REFERENCES DATACONNECTORS (NAME) ON DELETE CASCADE
);
ALTER TABLE DBS ADD TYPE VARCHAR2(32) DEFAULT 'NATIVE' NOT NULL;
ALTER TABLE DBS ADD DATACONNECTOR_NAME VARCHAR2(128) NULL;
ALTER TABLE DBS ADD REMOTE_DBNAME VARCHAR2(128) NULL;
UPDATE DBS SET TYPE='NATIVE' WHERE TYPE IS NULL;

CREATE TABLE DC_PRIVS (
  DC_GRANT_ID NUMBER NOT NULL,
  CREATE_TIME NUMBER (10) NOT NULL,
  NAME VARCHAR2(128) NULL,
  GRANT_OPTION NUMBER (5) NOT NULL,
  GRANTOR VARCHAR2(128) NULL,
  GRANTOR_TYPE VARCHAR2(128) NULL,
  PRINCIPAL_NAME VARCHAR2(128) NULL,
  PRINCIPAL_TYPE VARCHAR2(128) NULL,
  DC_PRIV VARCHAR2(128) NULL,
  AUTHORIZER VARCHAR2(128) NULL
);

ALTER TABLE DC_PRIVS ADD CONSTRAINT DC_PRIVS_PK PRIMARY KEY (DC_GRANT_ID);
ALTER TABLE DC_PRIVS ADD CONSTRAINT DC_PRIVS_FK1 FOREIGN KEY (NAME) REFERENCES DATACONNECTORS (NAME) INITIALLY DEFERRED ;
CREATE UNIQUE INDEX DBPRIVILEGEINDEX ON DC_PRIVS (AUTHORIZER,NAME,PRINCIPAL_NAME,PRINCIPAL_TYPE,DC_PRIV,GRANTOR,GRANTOR_TYPE);
CREATE INDEX DC_PRIVS_N49 ON DC_PRIVS (NAME);

-- These lines need to be last.  Insert any changes above.
UPDATE CDH_VERSION SET SCHEMA_VERSION='3.1.3000.7.2.16.0-Update1', VERSION_COMMENT='Hive release version 3.1.3000 for CDH 7.2.16.0-Update1' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 3.1.3000.7.2.15.0-Update6 to 3.1.3000.7.2.16.0-Update1' AS Status from dual;
