
-- HIVE-25656
ALTER TABLE MV_TABLES_USED ADD INSERTED_COUNT NUMBER DEFAULT 0 NOT NULL;
ALTER TABLE MV_TABLES_USED ADD UPDATED_COUNT NUMBER DEFAULT 0 NOT NULL;
ALTER TABLE MV_TABLES_USED ADD DELETED_COUNT NUMBER DEFAULT 0 NOT NULl;
ALTER TABLE MV_TABLES_USED ADD CONSTRAINT MV_TABLES_USED_PK PRIMARY KEY (TBL_ID, MV_CREATION_METADATA_ID);

-- HIVE-25993
ALTER TABLE COMPACTION_QUEUE ADD CQ_RETRY_RETENTION NUMBER(19) DEFAULT 0 NOT NULL;

-- These lines need to be last.  Insert any changes above.
UPDATE CDH_VERSION SET SCHEMA_VERSION='3.1.3000.7.2.15.0-Update3', VERSION_COMMENT='Hive release version 3.1.3000 for CDH 7.2.15.0-Update3' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 3.1.3000.7.2.15.0-Update2 to 3.1.3000.7.2.15.0-Update3' AS Status from dual;
