SELECT 'Upgrading MetaStore schema from 3.1.3000.7.2.15.0-Update5 to 3.1.3000.7.2.15.0-Update6' AS MESSAGE;

-- HIVE-26049
ALTER TABLE "TXN_COMPONENTS" ALTER COLUMN "TC_TABLE" nvarchar(256);
ALTER TABLE "COMPLETED_TXN_COMPONENTS" ALTER COLUMN "CTC_TABLE" nvarchar(256);
ALTER TABLE "HIVE_LOCKS" ALTER COLUMN "HL_TABLE" nvarchar(256);
ALTER TABLE "COMPACTION_QUEUE" ALTER COLUMN "CQ_TABLE" nvarchar(256) NOT NULL;
ALTER TABLE "COMPLETED_COMPACTIONS" ALTER COLUMN "CC_TABLE" nvarchar(256) NOT NULL;
ALTER TABLE "WRITE_SET" ALTER COLUMN "WS_TABLE" nvarchar(256) NOT NULL;
ALTER TABLE "TXN_WRITE_NOTIFICATION_LOG" DROP CONSTRAINT "TXN_WRITE_NOTIFICATION_LOG_PK";
ALTER TABLE "TXN_WRITE_NOTIFICATION_LOG" ALTER COLUMN "WNL_TABLE" nvarchar(256) NOT NULL;
ALTER TABLE "TXN_WRITE_NOTIFICATION_LOG" ADD CONSTRAINT "TXN_WRITE_NOTIFICATION_LOG_PK" PRIMARY KEY ("WNL_TXNID", "WNL_DATABASE", "WNL_TABLE", "WNL_PARTITION");

-- These lines need to be last.  Insert any changes above.
UPDATE CDH_VERSION SET SCHEMA_VERSION='3.1.3000.7.2.15.0-Update6', VERSION_COMMENT='Hive release version 3.1.3000 for CDH 7.2.15.0-Update6' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 3.1.3000.7.2.15.0-Update5 to 3.1.3000.7.2.15.0-Update6' AS MESSAGE;
