SELECT 'Upgrading MetaStore schema from 3.1.3000.7.2.15.0-Update6 to 7.2.16.0-Update1' AS MESSAGE;

-- HIVE-24396
-- Create DataConnectors and DataConnector_Params tables
CREATE TABLE `DATACONNECTORS` (
  `NAME` VARCHAR(128) NOT NULL,
  `TYPE` VARCHAR(32) NOT NULL,
  `URL` VARCHAR(4000) NOT NULL,
  `COMMENT` VARCHAR(256),
  `OWNER_NAME` VARCHAR(256),
  `OWNER_TYPE` VARCHAR(10),
  `CREATE_TIME` INT(11) NOT NULL,
  PRIMARY KEY (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `DATACONNECTOR_PARAMS` (
  `NAME` VARCHAR(128) NOT NULL,
  `PARAM_KEY` VARCHAR(180) NOT NULL,
  `PARAM_VALUE` VARCHAR(4000),
  PRIMARY KEY (`NAME`, `PARAM_KEY`),
  CONSTRAINT `DATACONNECTOR_NAME_FK1` FOREIGN KEY (`NAME`) REFERENCES `DATACONNECTORS` (`NAME`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `DBS` ADD COLUMN `TYPE` VARCHAR(32) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT 'NATIVE' NOT NULL;
ALTER TABLE `DBS` ADD COLUMN `DATACONNECTOR_NAME` VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_bin;
ALTER TABLE `DBS` ADD COLUMN `REMOTE_DBNAME` VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_bin;
UPDATE `DBS` SET `TYPE` = 'NATIVE' WHERE `TYPE` IS NULL;

CREATE TABLE IF NOT EXISTS `DC_PRIVS` (
  `DC_GRANT_ID` bigint(20) NOT NULL,
  `CREATE_TIME` int(11) NOT NULL,
  `NAME` VARCHAR(128) DEFAULT NULL,
  `GRANT_OPTION` smallint(6) NOT NULL,
  `GRANTOR` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `GRANTOR_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `PRINCIPAL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `PRINCIPAL_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `DC_PRIV` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `AUTHORIZER` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`DC_GRANT_ID`),
  UNIQUE KEY `DCPRIVILEGEINDEX` (`AUTHORIZER`,`NAME`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`DC_PRIV`,`GRANTOR`,`GRANTOR_TYPE`),
  KEY `DC_PRIVS_N49` (`NAME`),
  CONSTRAINT `DC_PRIVS_FK1` FOREIGN KEY (`NAME`) REFERENCES `DATACONNECTORS` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- These lines need to be last.  Insert any changes above.
UPDATE CDH_VERSION SET SCHEMA_VERSION='3.1.3000.7.2.16.0-Update1', VERSION_COMMENT='Hive release version 3.1.3000 for CDH 7.2.16.0-Update1' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 3.1.3000.7.2.15.0-Update6 to 3.1.3000.7.2.16.0-Update1';
